services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: davronov_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data:

